### ISSUE TITLE
Not for 0.16

### ISSUE THREAD

**Issue by StephanSteinert** [futileohm/factorio-naked-rails#2]
Hi,

please update to 0.16.

Made it for you: 
[naked-rails_1.0.1.zip](https://github.com/futileohm/factorio-naked-rails/files/1640499/naked-rails_1.0.1.zip)

Follow up with bugfixes:

**data.lua:**
30,31 change
data.raw["rail-remnants"]["straight-rail-remnants"].time_to_live = 0
data.raw["rail-remnants"]["curved-rail-remnants"].time_to_live = 0
to
data.raw["rail-remnants"]["straight-rail-remnants"].time_before_removed = 1073741824 
data.raw["rail-remnants"]["curved-rail-remnants"].time_before_removed = 1073741824

56,57,74,75,91,92,104,105,136,137,154,155,171,172,184,185 change
ptype.pictures[id[1]][element].sheet.filename = string.format("__naked-rails__/graphics/%s-transparent.png", id[2])
ptype.pictures[id[1]][element].sheet.hr_version.filename = string.format("__naked-rails__/graphics/hr-%s-transparent.png", id[2])

to

ptype.pictures[id[1]][element].filename = string.format("__naked-rails__/graphics/%s-transparent.png", id[2])
ptype.pictures[id[1]][element].hr_version.filename = string.format("__naked-rails__/graphics/hr-%s-transparent.png", id[2])

type = "selection-tool" add icon_size=32

**info.json:**
change 
 "factorio_version": "0.15",
to
"factorio_version": "0.16",

Additionally the picture hr-straight-rail-horizontal-transparent.png was not found so i made a new copy of hr-straight-rail-vertical-transparent.png and it seems fine

**Comment by futileohm** [comment]
Awesome, thanks for making these changes, I've merged your commits. I would love to hand the mod over to you to maintain going forward (if you'd like to), since I've been on break from Factorio for a while now and haven't touched 0.16 yet, but it looks like the mod portal doesn't have a way to do that.

I saw that you uploaded a 0.16 version of the mod to the mod portal under your name, if you'd prefer to maintain that one instead of trying to remove it at this point I'll point people to it from my mod description and that can be the 0.16+ version of the mod. I'll hold off on uploading the new version to the mod portal for a day or two to avoid confusion of having both if you'd like to do that.
